### ISSUE TITLE
Black flicker on resize

### ISSUE THREAD

**Issue by yhhl06** [martin-zyb/Remc#7]
#### Describe the bug
When ImGui resizes the window, it will flash black

#### Operating system:
- OS: Windows-64
- Version: Windows 10 IoT Enterprise LTSC

**Comment by martin-zyb** [comment]
This is a bug worth considering, and I will take action to address it.

**Comment by yhhl06** [comment]
> This is a bug worth considering, and I will take action to address it.

There is already a pull request (#8) resolving this.
